[package]
name = "detach"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.51", features = ["derive"] }
crossterm = "0.29.0"
portable-pty = "0.9.0"
vt100 = "0.16.2"
